name: CI Suite

on:
  pull_request:
    branches:
      - master
  merge_group:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  start_gate:
    if: ( !contains(github.event.head_commit.message, '[ci skip]') )
    name: Start Gate
    runs-on: ubuntu-latest
    steps:
      - name: Mandatory Empty Step
        run: exit 0

  run_linters:
    name: Run Linters
    needs: start_gate
    uses: ./.github/workflows/run_linters.yml





  completion_gate: # Serves as a non-moving target for branch rulesets
    name: Completion Gate
    needs:
      [
        # compile_all_maps,
        # run_all_tests,
        # run_alternate_tests,
        run_linters,
      ]
    runs-on: ubuntu-latest
    steps:
      - name: Mandatory Empty Step
        run: exit 0
































